# Generated by Django 4.2.5 on 2023-11-27 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.IntegerField(choices=[(1, 'Sales on cash'), (2, 'Sales in credit'), (3, 'Expense in cash'), (4, 'Expense on credit'), (5, 'Client Pays for sales on credit'), (6, 'Expense on credit paid'), (7, 'Equity Investment'), (8, 'Loan'), (9, 'Loan repayment')])),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('debit', models.FloatField(default=0)),
                ('credit', models.FloatField(default=0)),
                ('related_account', models.CharField(max_length=100)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.journalentry')),
            ],
        ),
    ]
